rewrites:
  - source: /inicio
    destination: /
  - source: /proyectos
    destination: /
  - source: /servicios
    destination: /
  - source: /curriculum
    destination: /
  - source: /contacto
    destination: /
